name: Deploy to EC2 using Docker and Docker Compose

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/chatbot-flask:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/chatbot-flask:latest

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd ../../Event-Chatbot
          git pull origin main
          docker pull oussamabenslama/chatbot-flask:latest
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d
        EOF
